name:               conduit-algorithms
version:            0.0.8.1
synopsis:           Conduit-based algorithms
category:           Conduit
author:             Luis Pedro Coelho
maintainer:         Luis Pedro Coelho
license:            MIT
license-file:       COPYING
github:             luispedro/conduit-algorithms
description: >
        Algorithms on Conduits, including higher level asynchronous processing
        and some other utilities.

extra-source-files:
 - README.md
 - ChangeLog
default-extensions:
 - BangPatterns
 - OverloadedStrings
 - LambdaCase
 - TupleSections
ghc-options:
 - -Wall
 - -O2

dependencies:
  - base > 4.8 && < 5
  - async
  - bytestring
  - bzlib-conduit
  - conduit >= 1.3
  - conduit-combinators >= 1.1.2
  - conduit-extra
  - containers
  - deepseq
  - exceptions
  - lz4-conduit
  - lzma-conduit
  - monad-control
  - mtl
  - pqueue
  - resourcet
  - streaming-commons
  - stm
  - stm-conduit >= 4.0
  - vector
  - unliftio-core
  - transformers

when:
  - condition: ! 'os(windows)'
    cpp-options: -DWINDOWS

library:
  exposed-modules:
    - Data.Conduit.Algorithms
    - Data.Conduit.Algorithms.Utils
    - Data.Conduit.Algorithms.Async
    - Data.Conduit.Algorithms.Async.ByteString
    - Data.Conduit.Algorithms.Storable
  other-modules: []

tests:
  conduit-algorithms-test:
    source-dirs: ./tests
    main: Tests.hs
    dependencies:
      - conduit-algorithms
      - directory
      - HUnit
      - test-framework
      - test-framework-hunit
      - test-framework-th

benchmarks:
  conduit-algorithms-bench:
    main: Bench.hs
    source-dirs: ./bench
    other-modules: []
    dependencies:
    - conduit-algorithms
    - criterion
    ghc-options:
    - -Wall
    - -fwarn-tabs
    - -fno-warn-missing-signatures
    - -threaded
    - -rtsopts
    - ! '"-with-rtsopts=-A64m -n4m -H"'

