resolver: lts-11.4

packages:
- .
extra-deps:
- lzma-clib-5.2.2

flags: {}

extra-package-dbs: []

nix:
    # Not enabled by default, but if --nix is passed on the command line, then
    # the other options will be used
    enable: false
    shell-file: shell.nix
